#!/bin/bash
#this is creating table script

DBName=$1
cd ..
cd DBs/$DBName


found=0

while [ true ]
do
	printf "Enter the name of New Table: " 
	read TableName
	if [ -z "$TableName" ];then
		echo please enter the Name of the Table.
	elif [[ $TableName == *" "* ]] || [[ $TableName == [1-9]* ]] || [[ $TableName == *['!'';''.'@#\$%^\&*()+-='\'?'/''`'~:,'<''>''['']']* ]] ;then
		echo not a good format
	elif [[ -f "$TableName" ]]; then
	  echo the Table Name already exist!
	else
	 break
	fi
done

while [ true ]
do
read -p "Enter the number of columns:" ColNum

if ! [[ "$ColNum" =~ ^[0-9]+$ ]];
then
echo Column number must be positive integer number 
elif [[ $ColNum -eq 0 ]]
then 
echo Enter at least 1 column 
else
break
fi
done



line1[0]="ID"
line2[0]="INTEGER"
i=1
export equal

while (( $i <= $ColNum ))
do


	while [ true ]
		do
                read -p "Enter the Column No.$i Name:" ColName
		if [ -z "$ColName" ];then
			echo please enter the Name of the column.


		elif [[ $ColName == *" "* ]] || [[ $ColName == [1-9]* ]] || [[ $ColName == *['!'';''.'@#\$%^\&*()+-='\'?'/''`'~:,'<''>''['']']* ]] ;then
			echo not a good format


		else

	  for col in ${line1[@]}
		  do
		  	
		    if [[ "$col" == "$ColName" ]]; then
			equal=1
			echo the column name already exist!

			break 
		    else
		    equal=0
		  
		    fi 
		  done

	  if [[ $equal == 0 ]];then
		  break
	  fi

	fi

done



line1[$i]=$ColName

        read -p "Choose data type for Column No.$i  (1)for INTEGER (2)for STRING:" choise
until [[ $choise == 1 ]] ||[[ $choise == 2 ]]
do

	echo Datetype must be  INTEGER or STRING
        read -p "Choose data type for Column No.$i  (1)for INTEGER (2)for STRING:" choise

done
if [[ $choise == 1 ]]
then

  line2[$i]="INTEGER"
else
  line2[$i]="STRING"	
fi

let i=$i+1

done

#to create table file and metadata file   
i=0
for var in  ${line1[@]}
do
if [[ $i == 0 ]];then
l1=$var
else
l1=$l1:$var
fi
let i=$i+1
done

echo  $l1 >> .$TableName
i=0

for var in  ${line2[@]}
do
if [[ $i == 0 ]];then
l2=$var
else
l2=$l2:$var
fi
let i=$i+1

done

echo  $l2 >> .$TableName

touch $TableName
echo Table $TableName Created Successfuly!


cd ..
cd ..
cd scripts

echo press enter to see the menu



