#!/bin/bash
#this is creating table script

DBName=$1
cd ..
cd DBs/$DBName


found=0
declare -a line1
declare -a line2

read -p "Enter the name of New Table:" TableName

while [ -z "$TableName" ];do
	echo please enter the Name of the Table.
        read -p "Enter the name of New Table:" TableName
done
while  [[ $TableName == *" "* ]] || [[ $TableName == [1-9]* ]] || [[ $TableName == *['!'@#\$%^\&*()_+]* ]] ;do
	echo not a good format
        read -p "Enter the name of New Table:" TableName
done
while [[ -f "$TableName" ]]; do
  echo the Table Name already exist!
  read -p "Enter the name of New Table:" TableName
done

echo Enter the number of columns
read ColNum
line1[0]="ID"
line2[0]="INTEGER"
i=1
while (( $i <= $ColNum ))
do
read -p "Enter the Column No.$i Name:" ColName
while [ -z "$ColName" ];do
	echo please enter the Name of the Column.
        read -p "Enter the Column No.$i Name:" ColName
done
while  [[ $ColName == *" "* ]] || [[ $ColName == [1-9]* ]] || [[ $ColName == *['!'@#\$%^\&*()_+]* ]] ;do


	echo not a good format
        read -p "Enter the Column No.$i Name:" ColName
done
for col in ${line1[@]}
do
	
while [[ "$col" == "$ColName" ]]; do
    echo the column name already exist!
    read -p "Enter the Column No.$i Name:" ColName
done
done

line1[$i]=$ColName

read -p "Choose data type for Column No.$i  (1)for INTEGER (2)for STRING:" choise
until [[ $choise == 1 ]] ||[[ $choise == 2 ]]
do
	echo Datetype must be  INTEGER or STRING
        read -p "Choose data type for Column No.$i  (1)for INTEGER (2)for STRING:" choise
done
if [[ $choise == 1 ]]
then

  line2[$i]="INTEGER"
else
  line2[$i]="STRING"	
fi

let i=$i+1

done

i=0
for var in  ${line1[@]}
do
if [[ $i == 0 ]];then
l1=$var
else
l1=$l1:$var
fi
let i=$i+1
done

echo  $l1 >> .$TableName
i=0

for var in  ${line2[@]}
do
if [[ $i == 0 ]];then
l2=$var
else
l2=$l2:$var
fi
let i=$i+1

done

echo  $l2 >> .$TableName


echo Table $TableName Created Successfuly!


cd ..
cd ..
cd scripts

echo press enter to see the menu




