#!/bin/bash
#this is creating table script

DBName=$1
cd ..
cd DBs/$DBName


found=0
declare -a line1 
declare -a line2 

read -p "Enter the name of New Table:" TableName
while [ true ]
do
if [ -z "$TableName" ];then
        echo please enter the Name of the Table.
        read -p "Enter the name of New Table again:" TableName
elif [[ $TableName == *" "* ]] || [[ $TableName == [1-9]* ]] || [[ $TableName == *['!'@#\$%^\&*()_+]* ]] ;then
	echo not a good format
        read -p "Enter the name of New Table agian:" TableName
elif [[ -f "$TableName" ]]; then
  echo the Table Name already exist!
  read -p "Enter the name of New Table again:" TableName
else
 break
fi
done

echo Enter the number of columns
read ColNum
line1[0]="ID"
line2[0]="INTEGER"
i=1
export equal
while (( $i <= $ColNum ))
do
read -p "Enter the Column No.$i Name:" ColName

while [ true ]
do
if [ -z "$ColName" ];then
        echo please enter the Name of the column.
        read -p "Enter the Column No.$i Name again:" ColName

elif [[ $ColName == *" "* ]] || [[ $ColName == [1-9]* ]] || [[ $ColName == *['!'@#\$%^\&*()_+]* ]] ;then
	echo not a good format
        read -p "Enter the Column No.$i Name again:" ColName

else

  for col in ${line1[@]}
  do
  	
    if [[ "$col" == "$ColName" ]]; then
        equal=1
        echo the column name already exist!
        read -p "Enter the Column No.$i Name again:" ColName
        break 
    else
    equal=0
  
    fi 
  done

  if [[ $equal == 0 ]];then
  break
  fi

fi

done



line1[$i]=$ColName

read -p "Choose data type for Column No.$i  (1)for INTEGER (2)for STRING:" choise
until [[ $choise == 1 ]] ||[[ $choise == 2 ]]
do
	echo Datetype must be  INTEGER or STRING
        read -p "Choose data type for Column No.$i  (1)for INTEGER (2)for STRING:" choise
done
if [[ $choise == 1 ]]
then

  line2[$i]="INTEGER"
else
  line2[$i]="STRING"	
fi

let i=$i+1

done

i=0
for var in  ${line1[@]}
do
if [[ $i == 0 ]];then
l1=$var
else
l1=$l1:$var
fi
let i=$i+1
done

echo  $l1 >> .$TableName
i=0

for var in  ${line2[@]}
do
if [[ $i == 0 ]];then
l2=$var
else
l2=$l2:$var
fi
let i=$i+1

done

echo  $l2 >> .$TableName

touch $TableName
echo Table $TableName Created Successfuly!


cd ..
cd ..
cd scripts

echo press enter to see the menu




