#!/bin/bash

DBName=$1
cd ..
cd DBs
count=1
if [ -d $DBName ];then
	echo the Tables at $DBName
	cd $DBName
	num=`ls`	
	echo \|=================\|
	for i in $num
	do
	printf "|%i %15s|\n" $count $i
	((count++))
	done
	echo \|=================\|

	cd ..
	cd ..
	cd scripts
elif [ -z "$DBName" ];then
	echo please enter the Name of the Table.
elif  [[ $DBName == *" "* ]] || [[ $DBName == [1-9]* ]] || [[ $DBName == *['!'@#\$%^\&*()_+]* ]] ;then
	echo not a good format

else
	echo DataBase not existed
	echo press enter to see the menu.
	cd ..
	cd scripts
fi


cd ..
cd scripts
