#!/bin/bash


DBName=$1
select var in  "Create Table"  "Delete Table"  "List Tables" "Show Table Structure"  "Open Table"  "Back"
do
clear

case $REPLY in

1 )  ./CreateTable $DBName;;
2 ) source ./DeleteTable $DBName ;;
3 ) source ./ListTables $DBName ;;
4 ) source ./TableStructure $DBName ;;
5 ) source ./OpenTable $DBName ;; #go lvl3
6 ) break ;;
*) echo $REPLY is not one of choises;;
esac
done
