#!/bin/bash
#this is layer3.sh script to show menu for layer3

select choise in "Show Content" "Insert Record" "Delete Record" "Update Record" "Search (Bonus)" "<-Back"
do	
	case $REPLY in
		1 ) 
			./ShowContent $1 $2;  # $1 holds DBName    $2 holds TableName
			;;
		2 )
			./InsertRecord $1 $2;
			;;
		3 )
			./DeleteRecord $1 $2;
			;;
		4 )
			./UpdateRecord $1 $2;
			;;
		5 ) 
			./Search $1 $2;
			;;
		6 )     break;; #go lvl2
		* )
			echo $REPLY is not one of choises;;
	esac
done


