#!/bin/bash


if [ ! -z "$1" ];then
DBName=$1
else
./ViewDB
echo enter DataBase name to Enter
read DBName
fi

cd ..
cd DBs

if [ -z $DBName ];then
	echo please enter the Name of the DataBase.
elif  [[ $DBName == *" "* ]] || [[ $DBName == [1-9]* ]] || [[ $DBName == *['!'@#\$%^\&*()_+]* ]] ;then
	echo not a good format
elif [ -d $DBName ];then

	cd ..
	cd scripts
     ./lvl2 $DBName
else
	echo DataBase not existed
        cd ..
	cd scripts
	
fi

echo press enter to see the menu


