#!/bin/bash

DBName=$1
TableName=$2

cd ..
cd DBs/$DBName/

	echo =================DataBase $DBName =================
	echo =================Table $TableName =================
	echo
	awk -F: '{if(NR==1){i=1;while(i<=NF){if(i==1){printf $i}else{ printf ("|%15s" ,$i) };i++}printf "|"}}' .$TableName
	echo
	awk -F: '{i=1;while(i<=NF){if(i==1){printf $i}else{printf ("|%15s" ,$i)};i++};print "|"}' $TableName

cd ..
cd ..
cd scripts
echo press enter to see the menu.
