#!/bin/bash

DBName=$1
./ListTables $DBName
cd ..
cd DBs/$DBName/

echo enter the name of the Table to view Structure
read TableName


if [ -z "$TableName" ];then
	echo please enter the Name of the Table.
elif  [[ $TableName == *" "* ]] || [[ $TableName == [1-9]* ]] || [[ $TableName == *['!'@#\$%^\&*()_+]* ]] ;then
	echo not a good format
elif [ -f $TableName ];then
colName=`awk -F: '{if(NR==1){i=1;while(i<=NF){print $i;i++}}}' .$TableName`
colType=`awk -F: '{if(NR==2){i=1;while(i<=NF){print $i;i++}}}' .$TableName`
count=1
i=1
printf  "%s Structure\n|===========================================|" $TableName
for var  in $colName
do
	j=1
	for x  in $colType
	do
		if [ $i -eq $j ];then
			if [ $i -eq 1 ];then
			printf "\n|%i %10s %10s PRIMARY KEY        |" $count $var $x 
			else
			printf "\n|%i %10s %10s                    |" $count $var $x 
			fi

		((count++))
		break
		fi
		((j++))
	done
((i++))
done 
printf  "\n|===========================================|\n"
else
	echo table not existed
fi

cd ..
cd ..
cd scripts
echo
echo press enter to see the menu.
