#!/bin/bash

DBName=$1
echo ===============$DBName==========
./ListTables $DBName
cd ..
cd DBs/$DBName/

echo enter the name of the Table to view Structure
read TableName


if [ -z "$TableName" ];then
	echo please enter the Name of the Table.
elif  [[ $TableName == *" "* ]] || [[ $TableName == [1-9]* ]] || [[ $TableName == *['!'@#\$%^\&*()_+]* ]] ;then
	echo not a good format
elif [ -f $TableName ];then
colName=`awk -F: '{if(NR==1){i=1;while(i<=NF){print $i;i++}}}' .$TableName`
colType=`awk -F: '{if(NR==2){i=1;while(i<=NF){if($i=="i"){$i="INTEGER"}else{$i="STRING"}print $i;i++}}}' .$TableName`

i=1
for var  in $colName
do
	j=1
	for x  in $colType
	do
		if [ $i -eq $j ];then
			if [ $i -eq 1 ];then
			echo $var "\\\\" $x "\\\\" PRIMARY KEY
			else
			echo $var "\\\\" $x
			#dialog --title 'this is the a table Structure' --msgbox  \'$var \\\\ $x\' 5 20
			fi
		break
		fi
		((j++))
	done
((i++))
done 

else
	echo table not existed
fi

cd ..
cd ..
cd scripts
echo press enter to see the menu.
