#!/bin/bash

cd ..
cd DBs
num=`ls`
count=1
if [ -z "$num" ];then
	echo no DataBases avilable.
else
	echo The DataBases are :
	echo DataBases
	echo \|=================\|
	for i in $num
	do	
		printf "|%i %15s|\n" $count $i
		((count++))
	done
	echo \|=================\|
fi

cd ..
cd scripts

